### PR TITLE
Feature/p2p messaging

### PR DESCRIPTION
**Pull request by jjang4001**
# Description
- Adds messaging over rtc only locally 
- Adds file transfers over rtc only locally
- I didn't clean up any code for now so its really messy :( but it works :), and I just wanted to get it out so i'm not blocking you in any way.

# Todo
- Clean up the code so that all the rtc logic isn't in both messaging and fileTransfer components
- Add testing for the behavior of the buttons and when we can use certain buttons
- Send the signals over the backend so we can have true p2p and not just signals to oneself

# Demo
### File Transfer
ezgif com-video-to-gif

### Messaging
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by jjang4001** [comment]
I also only tested this with pdfs.. So files of larger size might have other issues, but those will be RTC issues in general that we'll have to deal with but seems out of scope for now.

**Comment by jjang4001** [comment]
Oh I forgot to add that part to the UI. I was gonna make it display the speed of the file being received.

**Comment by afkim14** [comment]
Looks good!

**Comment by afkim14** [comment]
Looks good!

**Pull request merged**
